spring:
  application:
    name: TMS
  datasource:
    url: jdbc:postgresql://localhost:5432/
    #    url: jdbc:postgresql://database-1.ccjiqcskt4z6.eu-north-1.rds.amazonaws.com:5432/VentureVerse
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 60MB
